services:
  backend:
    image: backend
    build:
      context: Backend
      dockerfile: ./Dockerfile
    env_file:
      - .env
    environment:
      NODE_ENV: production
    ports:
      - 8081:8080
    depends_on:
      - mongo
      - redis
    networks:
      - chatraj-net

  frontend:
    image: frontend
    build:
      context: frontend
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      VITE_BACKEND_URL: http://backend:8080
    ports:
      - 3080:3080
    networks:
      - chatraj-net

  mongo:
    image: mongo:7
    restart: always
    networks:
      - chatraj-net

  redis:
    image: redis:7
    restart: always
    networks:
      - chatraj-net

networks:
  chatraj-net:
    driver: bridge
