services:
  - type: web
    name: chatraj-backend
    env: node
    rootDir: Backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 16.20.2
    healthCheckPath: /health
    nodeVersion: 18.x