import PropTypes from 'prop-types';
import {
    Description,
    Html,
    Css,
    Javascript,
    Code,
    DataObject,
    Storage,
    FolderZip,
    Image,
    PictureAsPdf,
    Article,
    Lock,
    VpnKey,
    Terminal,
    Apple,
    Android,
    Build,
    BugReport,
    SportsEsports,
    Cloud,
    Security,
    Schema,
    Settings,
} from '@mui/icons-material';

const FileIcon = ({ fileName }) => {
    const getIcon = (fileName) => {
        const ext = fileName.split('.').pop().toLowerCase();

        const iconMap = {
            html: <Html />,
            css: <Css />,
            scss: <Css />,
            sass: <Css />,
            less: <Css />,
            js: <Javascript />,
            jsx: <Javascript />,
            ts: <Javascript />,
            tsx: <Javascript />,
            vue: <Javascript />,
            php: <Code />,
            py: <Code />,
            java: <Code />,
            class: <Code />,
            jar: <Code />,
            rs: <Code />,
            go: <Code />,
            rb: <Code />,
            rake: <Code />,
            pl: <Code />,
            scala: <Code />,
            cs: <Code />,
            fs: <Code />,
            cpp: <Code />,
            cc: <Code />,
            c: <Code />,
            h: <Code />,
            hpp: <Code />,
            json: <DataObject />,
            yaml: <Article />,
            yml: <Article />,
            xml: <DataObject />,
            toml: <Article />,
            ini: <Settings />,
            env: <VpnKey />,
            md: <Article />,
            mdx: <Article />,
            txt: <Description />,
            doc: <Article />,
            docx: <Article />,
            pdf: <PictureAsPdf />,
            sql: <Storage />,
            mysql: <Storage />,
            pgsql: <Storage />,
            mongo: <Storage />,
            redis: <Storage />,
            lock: <Lock />,
            sh: <Terminal />,
            bash: <Terminal />,
            zsh: <Terminal />,
            bat: <Terminal />,
            ps1: <Terminal />,
            swift: <Apple />,
            kt: <Android />,
            gradle: <Android />,
            xcodeproj: <Apple />,
            git: <Build />,
            gitignore: <Build />,
            dockerfile: <Build />,
            docker: <Build />,
            jenkinsfile: <Build />,
            test: <BugReport />,
            spec: <BugReport />,
            svg: <Image />,
            png: <Image />,
            jpg: <Image />,
            jpeg: <Image />,
            gif: <Image />,
            ico: <Image />,
            webp: <Image />,
            ttf: <Code />,
            otf: <Code />,
            woff: <Code />,
            woff2: <Code />,
            unity: <SportsEsports />,
            blend: <SportsEsports />,
            fbx: <SportsEsports />,
            obj: <SportsEsports />,
            tf: <Cloud />,
            cfn: <Cloud />,
            redux: <Storage />,
            zustand: <Storage />,
            mobx: <Storage />,
            wasm: <Code />,
            wat: <Code />,
            key: <VpnKey />,
            pem: <VpnKey />,
            crt: <Security />,
            cer: <Security />,
            proto: <Schema />,
            graphql: <Schema />,
            gql: <Schema />,
            eslintrc: <Settings />,
            prettierrc: <Settings />,
            babelrc: <Settings />,
            webpack: <Settings />,
            rollup: <Settings />,
            vite: <Settings />,
            gemfile: <Code />,
            podfile: <Code />,
            cargo: <Code />,
            log: <Article />,
            csv: <Article />,
            tsv: <Article />,
            zip: <FolderZip />,
            rar: <FolderZip />,
            tar: <FolderZip />,
            gz: <FolderZip />,
            default: <Description />
        };

        return iconMap[ext] || iconMap.default;
    };

    return getIcon(fileName);
};

FileIcon.propTypes = {
    fileName: PropTypes.string.isRequired,
};

export default FileIcon;