name: Auto-Approve PRs by Admin

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  auto-approve:
    if: github.actor == 'Abhirajgautam28'
    runs-on: ubuntu-latest
    steps:
      - name: Auto-approve PR
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.GH_PAT }}
          message: 'Auto-approved by Abhirajgautam28'