name: Close PR if Deployment Fails

on:
  deployment_status:

jobs:
  close-pr-on-failure:
    if: github.event.deployment_status.state == 'failure'
    runs-on: ubuntu-latest

    steps:
      - name: Find Pull Request for Deployment SHA
        uses: jwalton/gh-find-current-pr@v1
        id: find_pr
        with:
          github-token: ${{ secrets.GH_PAT }}

      - name: Close the PR
        if: steps.find_pr.outputs.number != ''
        uses: peter-evans/close-pull@v3
        with:
          pull-request-number: ${{ steps.find_pr.outputs.number }}
          comment: |
            🚫 This PR has been closed automatically because the deployment failed.
          token: ${{ secrets.GH_PAT }}
