name: Auto Label Own PRs

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  label:
    runs-on: ubuntu-latest
    if: github.actor == github.event.pull_request.user.login
    steps:
      - name: Add 'automerge' label to own PR
        run: gh pr edit "$PR_URL" --add-label "automerge"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}