name: Auto Label PRs

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  label:
    if: github.actor == 'Abhirajgautam28'
    runs-on: ubuntu-latest
    steps:
      - name: Add automerge label to self PRs
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: automerge