name: Label own PRs as automerge

on:
  pull_request:
    types: [opened]

jobs:
  label:
    if: github.actor == github.event.pull_request.user.login
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ['automerge']
            })