name: Label Own PRs

on:
  pull_request_target:
    types: [opened, reopened]

jobs:
  label:
    if: github.actor == 'Abhirajgautam28'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Add automerge label to your own PR
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: automerge