name: Enable Auto-Merge for Own PRs

on:
  pull_request:
    types: [labeled]

jobs:
  enable-auto-merge:
    if: github.actor == github.event.pull_request.user.login && contains(github.event.pull_request.labels.*.name, 'automerge')
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write

    steps:
    - uses: actions/github-script@v7
      with:
        script: |
          github.rest.pulls.enableAutoMerge({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number,
            merge_method: "squash"
          })